#!/usr/bin/env bash
# Writes ios/Flutter/CI-Signing.xcconfig for manual codesign during CI builds.
set -euo pipefail

TEAM_ID="${IOS_TEAM_ID:?Set IOS_TEAM_ID secret}"
PROFILE_NAME="${IOS_PROVISIONING_PROFILE_NAME:?Set IOS_PROVISIONING_PROFILE_NAME secret}"
IDENTITY="${IOS_CODE_SIGN_IDENTITY:-Apple Distribution}"

OUT="ios/Flutter/CI-Signing.xcconfig"
cat > "$OUT" <<EOF
// Auto-generated by GitHub Actions — do not commit.
DEVELOPMENT_TEAM=${TEAM_ID}
CODE_SIGN_STYLE=Manual
CODE_SIGN_IDENTITY=${IDENTITY}
PROVISIONING_PROFILE_SPECIFIER=${PROFILE_NAME}
EOF

echo "Wrote ${OUT}"
